export enum SCREENS {
  BOTTOM_TAB_NAVIGATION = "BOTTOM_TAB_NAVIGATION",
  // ------- Home stack
  AUTH_STACK = "AUTH_STACK",

  // ------- Home stack
  HOME_STACK = "HOME_STACK",
  HOME_SCREEN = "HOME_SCREEN",

  // ------- Account stack
  ACCOUNT_STACK = "ACCOUNT_STACK",
  HOME_ACCOUNT_SCREEN = "HOME_ACCOUNT_SCREEN",
  ACCOUNT_INFORMATION_SCREEN = "ACCOUNT_INFORMATION_SCREEN",
}
