export enum SCREENS {
  LAUNCH_SCREEN= "LAUNCH_SCREEN",
  BOTTOM_TAB_NAVIGATION = "BOTTOM_TAB_NAVIGATION",
  // ------- Authentication stack
  AUTH_STACK = "AUTH_STACK",
  LOGIN_SCREEN = "LOGIN_SCREEN",

  // ------- Home stack
  HOME_STACK = "HOME_STACK",
  HOME_SCREEN = "HOME_SCREEN",

  // ------- Account stack
  ACCOUNT_STACK = "ACCOUNT_STACK",
  HOME_ACCOUNT_SCREEN = "HOME_ACCOUNT_SCREEN",
  ACCOUNT_INFORMATION_SCREEN = "ACCOUNT_INFORMATION_SCREEN",
}
